run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor/
    - third_party/

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - gocritic
    - goconst
    - gocognit
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - interfacer
    - lll
    - nakedret
    - prealloc
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - stylecheck
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
    - wsl

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  gomnd:
    settings:
      mnd:
        checks: argument,assign,case,condition,operation,return
  gosec:
    excludes:
      - G404  # Use of weak random number generator
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - wrapperFunc
      - dupImport
      - ifElseChain
      - octalLiteral

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - text: "should have comment"
      linters:
        - golint
    - text: "error strings should not be capitalized"
      linters:
        - golint
    - text: "should have comment or be unexported"
      linters:
        - golint

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

path:
  skip-dirs:
    - vendor/
    - third_party/
    - testdata/
    - examples/
    - Godeps/
    - builtin/ 