run:
  modules-download-mode: readonly
  timeout: 5m
  exclude-dirs:
    - vendor
    - testdata

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused

issues:
  exclude-use-default: false
