version: '3.8'

services:
  postgres:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: isolation_db
      POSTGRES_USER: isolation_user
      POSTGRES_PASSWORD: isolation_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U isolation_user -d isolation_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 